// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aggregate/batch.proto

package aggregate

import (
	bytes "bytes"
	encoding_binary "encoding/binary"
	fmt "fmt"
	point "github.com/GuanceCloud/cliutils/point"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AlgoMethod int32

const (
	METHOD_UNSPECIFIED AlgoMethod = 0
	SUM                AlgoMethod = 1
	AVG                AlgoMethod = 2
	COUNT              AlgoMethod = 3
	MIN                AlgoMethod = 4
	MAX                AlgoMethod = 5
	HISTOGRAM          AlgoMethod = 6
	EXPO_HISTOGRAM     AlgoMethod = 7
	STDEV              AlgoMethod = 8
	QUANTILES          AlgoMethod = 9
	COUNT_DISTINCT     AlgoMethod = 10
	LAST               AlgoMethod = 11
	FIRST              AlgoMethod = 12
)

var AlgoMethod_name = map[int32]string{
	0:  "METHOD_UNSPECIFIED",
	1:  "SUM",
	2:  "AVG",
	3:  "COUNT",
	4:  "MIN",
	5:  "MAX",
	6:  "HISTOGRAM",
	7:  "EXPO_HISTOGRAM",
	8:  "STDEV",
	9:  "QUANTILES",
	10: "COUNT_DISTINCT",
	11: "LAST",
	12: "FIRST",
}

var AlgoMethod_value = map[string]int32{
	"METHOD_UNSPECIFIED": 0,
	"SUM":                1,
	"AVG":                2,
	"COUNT":              3,
	"MIN":                4,
	"MAX":                5,
	"HISTOGRAM":          6,
	"EXPO_HISTOGRAM":     7,
	"STDEV":              8,
	"QUANTILES":          9,
	"COUNT_DISTINCT":     10,
	"LAST":               11,
	"FIRST":              12,
}

func (AlgoMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdceb39e44392377, []int{0}
}

type AggregationBatch struct {
	RoutingKey uint64 `protobuf:"varint,1,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	ConfigHash uint64 `protobuf:"varint,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// raw toml configures
	RawConfig       []byte                      `protobuf:"bytes,3,opt,name=raw_config,json=rawConfig,proto3" json:"raw_config,omitempty"`
	AggregationOpts map[string]*AggregationAlgo `protobuf:"bytes,4,rep,name=aggregation_opts,json=aggregationOpts,proto3" json:"aggregation_opts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Points          *point.PBPoints             `protobuf:"bytes,5,opt,name=points,proto3" json:"points,omitempty"`
}

func (m *AggregationBatch) Reset()      { *m = AggregationBatch{} }
func (*AggregationBatch) ProtoMessage() {}
func (*AggregationBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdceb39e44392377, []int{0}
}
func (m *AggregationBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AggregationBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AggregationBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AggregationBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationBatch.Merge(m, src)
}
func (m *AggregationBatch) XXX_Size() int {
	return m.Size()
}
func (m *AggregationBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationBatch.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationBatch proto.InternalMessageInfo

func (m *AggregationBatch) GetRoutingKey() uint64 {
	if m != nil {
		return m.RoutingKey
	}
	return 0
}

func (m *AggregationBatch) GetConfigHash() uint64 {
	if m != nil {
		return m.ConfigHash
	}
	return 0
}

func (m *AggregationBatch) GetRawConfig() []byte {
	if m != nil {
		return m.RawConfig
	}
	return nil
}

func (m *AggregationBatch) GetAggregationOpts() map[string]*AggregationAlgo {
	if m != nil {
		return m.AggregationOpts
	}
	return nil
}

func (m *AggregationBatch) GetPoints() *point.PBPoints {
	if m != nil {
		return m.Points
	}
	return nil
}

type AggregationAlgo struct {
	// 1. which algorithm to apply for specific field?
	Method AlgoMethod `protobuf:"varint,1,opt,name=method,proto3,enum=aggregate.v1.AlgoMethod" json:"method,omitempty"`
	// 2. what the origin field name of the data?
	SourceField string `protobuf:"bytes,2,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`
	Window      int64  `protobuf:"varint,3,opt,name=window,proto3" json:"window,omitempty"`
	// Types that are valid to be assigned to Options:
	//	*AggregationAlgo_HistogramOpts
	//	*AggregationAlgo_ExpoOpts
	//	*AggregationAlgo_QuantileOpts
	Options isAggregationAlgo_Options `protobuf_oneof:"options"`
	AddTags map[string]string         `protobuf:"bytes,8,rep,name=add_tags,json=addTags,proto3" json:"add_tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *AggregationAlgo) Reset()      { *m = AggregationAlgo{} }
func (*AggregationAlgo) ProtoMessage() {}
func (*AggregationAlgo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdceb39e44392377, []int{1}
}
func (m *AggregationAlgo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AggregationAlgo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AggregationAlgo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AggregationAlgo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationAlgo.Merge(m, src)
}
func (m *AggregationAlgo) XXX_Size() int {
	return m.Size()
}
func (m *AggregationAlgo) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationAlgo.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationAlgo proto.InternalMessageInfo

type isAggregationAlgo_Options interface {
	isAggregationAlgo_Options()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type AggregationAlgo_HistogramOpts struct {
	HistogramOpts *HistogramOptions `protobuf:"bytes,10,opt,name=histogram_opts,json=histogramOpts,proto3,oneof" json:"histogram_opts,omitempty"`
}
type AggregationAlgo_ExpoOpts struct {
	ExpoOpts *ExpoHistogramOptions `protobuf:"bytes,11,opt,name=expo_opts,json=expoOpts,proto3,oneof" json:"expo_opts,omitempty"`
}
type AggregationAlgo_QuantileOpts struct {
	QuantileOpts *QuantileOptions `protobuf:"bytes,12,opt,name=quantile_opts,json=quantileOpts,proto3,oneof" json:"quantile_opts,omitempty"`
}

func (*AggregationAlgo_HistogramOpts) isAggregationAlgo_Options() {}
func (*AggregationAlgo_ExpoOpts) isAggregationAlgo_Options()      {}
func (*AggregationAlgo_QuantileOpts) isAggregationAlgo_Options()  {}

func (m *AggregationAlgo) GetOptions() isAggregationAlgo_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *AggregationAlgo) GetMethod() AlgoMethod {
	if m != nil {
		return m.Method
	}
	return METHOD_UNSPECIFIED
}

func (m *AggregationAlgo) GetSourceField() string {
	if m != nil {
		return m.SourceField
	}
	return ""
}

func (m *AggregationAlgo) GetWindow() int64 {
	if m != nil {
		return m.Window
	}
	return 0
}

func (m *AggregationAlgo) GetHistogramOpts() *HistogramOptions {
	if x, ok := m.GetOptions().(*AggregationAlgo_HistogramOpts); ok {
		return x.HistogramOpts
	}
	return nil
}

func (m *AggregationAlgo) GetExpoOpts() *ExpoHistogramOptions {
	if x, ok := m.GetOptions().(*AggregationAlgo_ExpoOpts); ok {
		return x.ExpoOpts
	}
	return nil
}

func (m *AggregationAlgo) GetQuantileOpts() *QuantileOptions {
	if x, ok := m.GetOptions().(*AggregationAlgo_QuantileOpts); ok {
		return x.QuantileOpts
	}
	return nil
}

func (m *AggregationAlgo) GetAddTags() map[string]string {
	if m != nil {
		return m.AddTags
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AggregationAlgo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AggregationAlgo_HistogramOpts)(nil),
		(*AggregationAlgo_ExpoOpts)(nil),
		(*AggregationAlgo_QuantileOpts)(nil),
	}
}

type HistogramOptions struct {
	// for explict histogram(e.g.  10, 50, 100)
	Buckets []float64 `protobuf:"fixed64,1,rep,packed,name=buckets,proto3" json:"buckets,omitempty"`
}

func (m *HistogramOptions) Reset()      { *m = HistogramOptions{} }
func (*HistogramOptions) ProtoMessage() {}
func (*HistogramOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdceb39e44392377, []int{2}
}
func (m *HistogramOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistogramOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistogramOptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistogramOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistogramOptions.Merge(m, src)
}
func (m *HistogramOptions) XXX_Size() int {
	return m.Size()
}
func (m *HistogramOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_HistogramOptions.DiscardUnknown(m)
}

var xxx_messageInfo_HistogramOptions proto.InternalMessageInfo

func (m *HistogramOptions) GetBuckets() []float64 {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type ExpoHistogramOptions struct {
	MaxScale     int32 `protobuf:"varint,1,opt,name=max_scale,json=maxScale,proto3" json:"max_scale,omitempty"`
	MaxBuckets   int32 `protobuf:"varint,2,opt,name=max_buckets,json=maxBuckets,proto3" json:"max_buckets,omitempty"`
	RecordMinMax bool  `protobuf:"varint,3,opt,name=record_min_max,json=recordMinMax,proto3" json:"record_min_max,omitempty"`
}

func (m *ExpoHistogramOptions) Reset()      { *m = ExpoHistogramOptions{} }
func (*ExpoHistogramOptions) ProtoMessage() {}
func (*ExpoHistogramOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdceb39e44392377, []int{3}
}
func (m *ExpoHistogramOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExpoHistogramOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExpoHistogramOptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExpoHistogramOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpoHistogramOptions.Merge(m, src)
}
func (m *ExpoHistogramOptions) XXX_Size() int {
	return m.Size()
}
func (m *ExpoHistogramOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpoHistogramOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ExpoHistogramOptions proto.InternalMessageInfo

func (m *ExpoHistogramOptions) GetMaxScale() int32 {
	if m != nil {
		return m.MaxScale
	}
	return 0
}

func (m *ExpoHistogramOptions) GetMaxBuckets() int32 {
	if m != nil {
		return m.MaxBuckets
	}
	return 0
}

func (m *ExpoHistogramOptions) GetRecordMinMax() bool {
	if m != nil {
		return m.RecordMinMax
	}
	return false
}

type QuantileOptions struct {
	// The target percentiles (e.g. 0.50, 0.99)
	Percentiles []float64 `protobuf:"fixed64,1,rep,packed,name=percentiles,proto3" json:"percentiles,omitempty"`
}

func (m *QuantileOptions) Reset()      { *m = QuantileOptions{} }
func (*QuantileOptions) ProtoMessage() {}
func (*QuantileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdceb39e44392377, []int{4}
}
func (m *QuantileOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuantileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuantileOptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuantileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuantileOptions.Merge(m, src)
}
func (m *QuantileOptions) XXX_Size() int {
	return m.Size()
}
func (m *QuantileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_QuantileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_QuantileOptions proto.InternalMessageInfo

func (m *QuantileOptions) GetPercentiles() []float64 {
	if m != nil {
		return m.Percentiles
	}
	return nil
}

func init() {
	proto.RegisterEnum("aggregate.v1.AlgoMethod", AlgoMethod_name, AlgoMethod_value)
	proto.RegisterType((*AggregationBatch)(nil), "aggregate.v1.AggregationBatch")
	proto.RegisterMapType((map[string]*AggregationAlgo)(nil), "aggregate.v1.AggregationBatch.AggregationOptsEntry")
	proto.RegisterType((*AggregationAlgo)(nil), "aggregate.v1.AggregationAlgo")
	proto.RegisterMapType((map[string]string)(nil), "aggregate.v1.AggregationAlgo.AddTagsEntry")
	proto.RegisterType((*HistogramOptions)(nil), "aggregate.v1.HistogramOptions")
	proto.RegisterType((*ExpoHistogramOptions)(nil), "aggregate.v1.ExpoHistogramOptions")
	proto.RegisterType((*QuantileOptions)(nil), "aggregate.v1.QuantileOptions")
}

func init() { proto.RegisterFile("aggregate/batch.proto", fileDescriptor_fdceb39e44392377) }

var fileDescriptor_fdceb39e44392377 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xcf, 0x6e, 0xdb, 0x46,
	0x10, 0xc6, 0xb9, 0xa2, 0xf5, 0x87, 0x43, 0xda, 0xde, 0x2e, 0xdc, 0x80, 0x70, 0x11, 0x56, 0x15,
	0x0a, 0x54, 0x08, 0x0a, 0xb9, 0xb5, 0x2f, 0x45, 0x7a, 0xa2, 0x2c, 0xda, 0x22, 0x1a, 0x49, 0x0e,
	0x49, 0x07, 0x41, 0x0f, 0x25, 0xd6, 0x22, 0x43, 0x11, 0x91, 0xb8, 0x0c, 0x49, 0xc5, 0x72, 0x4f,
	0x7d, 0x84, 0x3e, 0x46, 0x5f, 0xa1, 0x6f, 0xd0, 0xa3, 0x8f, 0x39, 0xb5, 0xb5, 0x7c, 0xe9, 0x31,
	0x8f, 0x50, 0x70, 0x29, 0x59, 0xb2, 0xa0, 0xf6, 0x22, 0xec, 0xfe, 0xe6, 0xdb, 0x6f, 0x67, 0x66,
	0x47, 0x84, 0x4f, 0x69, 0x10, 0x24, 0x7e, 0x40, 0x33, 0xff, 0xe8, 0x8a, 0x66, 0xc3, 0x51, 0x2b,
	0x4e, 0x58, 0xc6, 0x88, 0xf2, 0x80, 0x5b, 0xef, 0xbf, 0x3d, 0xfc, 0x24, 0x66, 0x61, 0x94, 0x1d,
	0xf1, 0xdf, 0x42, 0xd0, 0xf8, 0xab, 0x04, 0x58, 0x5f, 0x68, 0x42, 0x16, 0xb5, 0xf3, 0xb3, 0xe4,
	0x73, 0x90, 0x13, 0x36, 0xcd, 0xc2, 0x28, 0x70, 0xdf, 0xfa, 0x37, 0x2a, 0xaa, 0xa3, 0xe6, 0x8e,
	0x05, 0x0b, 0xf4, 0x83, 0x7f, 0x93, 0x0b, 0x86, 0x2c, 0x7a, 0x13, 0x06, 0xee, 0x88, 0xa6, 0x23,
	0xb5, 0x54, 0x08, 0x0a, 0xd4, 0xa5, 0xe9, 0x88, 0x3c, 0x05, 0x48, 0xe8, 0xb5, 0x5b, 0x10, 0x55,
	0xac, 0xa3, 0xa6, 0x62, 0x49, 0x09, 0xbd, 0x3e, 0xe5, 0x80, 0xfc, 0x04, 0x98, 0xae, 0x2e, 0x75,
	0x59, 0x9c, 0xa5, 0xea, 0x4e, 0x5d, 0x6c, 0xca, 0xc7, 0x27, 0xad, 0xf5, 0x8c, 0x5b, 0x9b, 0xa9,
	0xad, 0x83, 0x41, 0x9c, 0xa5, 0x46, 0x94, 0x25, 0x37, 0xd6, 0x3e, 0x7d, 0x4c, 0xc9, 0x57, 0x50,
	0xe1, 0x45, 0xa6, 0x6a, 0xb9, 0x8e, 0x9a, 0xf2, 0xf1, 0x7e, 0xab, 0xa8, 0xf9, 0xa2, 0x7d, 0xc1,
	0xb1, 0xb5, 0x08, 0x1f, 0x52, 0x38, 0xd8, 0xe6, 0x48, 0x30, 0x88, 0xcb, 0xca, 0x25, 0x2b, 0x5f,
	0x92, 0x13, 0x28, 0xbf, 0xa7, 0xe3, 0xa9, 0xcf, 0x8b, 0x95, 0x8f, 0x9f, 0xfe, 0x67, 0x9e, 0xfa,
	0x38, 0x60, 0x56, 0xa1, 0x7d, 0x5e, 0xfa, 0x0e, 0x35, 0xfe, 0x14, 0x61, 0x7f, 0x23, 0x4c, 0xbe,
	0x81, 0xca, 0xc4, 0xcf, 0x46, 0xcc, 0xe3, 0x37, 0xec, 0x1d, 0xab, 0x1b, 0x6e, 0xe3, 0x80, 0xf5,
	0x78, 0xdc, 0x5a, 0xe8, 0xc8, 0x17, 0xa0, 0xa4, 0x6c, 0x9a, 0x0c, 0x7d, 0xf7, 0x4d, 0xe8, 0x8f,
	0x3d, 0x9e, 0x85, 0x64, 0xc9, 0x05, 0x3b, 0xcb, 0x11, 0x79, 0x02, 0x95, 0xeb, 0x30, 0xf2, 0xd8,
	0x35, 0xef, 0xb7, 0x68, 0x2d, 0x76, 0xe4, 0x1c, 0xf6, 0x46, 0x61, 0x9a, 0xb1, 0x20, 0xa1, 0x93,
	0xa2, 0xd5, 0xc0, 0x4b, 0xd0, 0x1e, 0x5f, 0xda, 0x5d, 0x6a, 0x06, 0x71, 0x9e, 0x67, 0xda, 0x15,
	0xac, 0xdd, 0xd1, 0x1a, 0x4b, 0x89, 0x0e, 0x92, 0x3f, 0x8b, 0x59, 0xe1, 0x21, 0x73, 0x8f, 0xc6,
	0x63, 0x0f, 0x63, 0x16, 0xb3, 0x2d, 0x3e, 0xb5, 0xfc, 0x18, 0xb7, 0xe8, 0xc0, 0xee, 0xbb, 0x29,
	0x8d, 0xb2, 0x70, 0xec, 0x17, 0x36, 0xca, 0xb6, 0x6e, 0xbe, 0x5c, 0x48, 0x56, 0x0e, 0xca, 0xbb,
	0x15, 0x4a, 0x89, 0x01, 0x35, 0xea, 0x79, 0x6e, 0x46, 0x83, 0x54, 0xad, 0xf1, 0xb1, 0x79, 0xf6,
	0xbf, 0xcf, 0xd1, 0xd2, 0x3d, 0xcf, 0xa1, 0xc1, 0x62, 0x5a, 0xaa, 0xb4, 0xd8, 0x1d, 0x3e, 0x07,
	0x65, 0x3d, 0xb0, 0xe5, 0xd1, 0x0f, 0xd6, 0x1f, 0x5d, 0x5a, 0x7b, 0xd5, 0xb6, 0x04, 0x55, 0x56,
	0x64, 0xd7, 0xf8, 0x1a, 0xf0, 0x66, 0xcd, 0x44, 0x85, 0xea, 0xd5, 0x74, 0xf8, 0xd6, 0xcf, 0x52,
	0x15, 0xd5, 0xc5, 0x26, 0xb2, 0x96, 0xdb, 0xc6, 0xcf, 0x70, 0xb0, 0xad, 0x4b, 0xe4, 0x33, 0x90,
	0x26, 0x74, 0xe6, 0xa6, 0x43, 0x3a, 0xf6, 0x79, 0x0a, 0x65, 0xab, 0x36, 0xa1, 0x33, 0x3b, 0xdf,
	0xe7, 0xff, 0xb7, 0x3c, 0xb8, 0xb4, 0x2c, 0xf1, 0x30, 0x4c, 0xe8, 0xac, 0x5d, 0x10, 0xf2, 0x25,
	0xec, 0x25, 0xfe, 0x90, 0x25, 0x9e, 0x3b, 0x09, 0x23, 0x77, 0x42, 0x67, 0x7c, 0x06, 0x6a, 0x96,
	0x52, 0xd0, 0x5e, 0x18, 0xf5, 0xe8, 0xac, 0x71, 0x02, 0xfb, 0x1b, 0xad, 0x25, 0x75, 0x90, 0x63,
	0x3f, 0x19, 0xfa, 0x1c, 0x2e, 0x93, 0x5d, 0x47, 0xcf, 0x7e, 0x47, 0x00, 0xab, 0x81, 0x24, 0x4f,
	0x80, 0xf4, 0x0c, 0xa7, 0x3b, 0xe8, 0xb8, 0x97, 0x7d, 0xfb, 0xc2, 0x38, 0x35, 0xcf, 0x4c, 0xa3,
	0x83, 0x05, 0x52, 0x05, 0xd1, 0xbe, 0xec, 0x61, 0x94, 0x2f, 0xf4, 0x57, 0xe7, 0xb8, 0x44, 0x24,
	0x28, 0x9f, 0x0e, 0x2e, 0xfb, 0x0e, 0x16, 0x73, 0xd6, 0x33, 0xfb, 0x78, 0x87, 0x2f, 0xf4, 0xd7,
	0xb8, 0x4c, 0x76, 0x41, 0xea, 0x9a, 0xb6, 0x33, 0x38, 0xb7, 0xf4, 0x1e, 0xae, 0x10, 0x02, 0x7b,
	0xc6, 0xeb, 0x8b, 0x81, 0xbb, 0x62, 0xd5, 0xfc, 0xbc, 0xed, 0x74, 0x8c, 0x57, 0xb8, 0x96, 0xab,
	0x5f, 0x5e, 0xea, 0x7d, 0xc7, 0x7c, 0x61, 0xd8, 0x58, 0xca, 0xd5, 0xdc, 0xd9, 0xed, 0x98, 0xb6,
	0x63, 0xf6, 0x4f, 0x1d, 0x0c, 0xa4, 0x06, 0x3b, 0x2f, 0x74, 0xdb, 0xc1, 0x72, 0x7e, 0xee, 0xcc,
	0xb4, 0x6c, 0x07, 0x2b, 0x6d, 0xfd, 0xf6, 0x4e, 0x13, 0x3e, 0xdc, 0x69, 0xc2, 0xc7, 0x3b, 0x0d,
	0xfd, 0x32, 0xd7, 0xd0, 0x6f, 0x73, 0x0d, 0xfd, 0x31, 0xd7, 0xd0, 0xed, 0x5c, 0x43, 0x7f, 0xcf,
	0x35, 0xf4, 0xcf, 0x5c, 0x13, 0x3e, 0xce, 0x35, 0xf4, 0xeb, 0xbd, 0x26, 0xdc, 0xde, 0x6b, 0xc2,
	0x87, 0x7b, 0x4d, 0xf8, 0x51, 0x3e, 0xfa, 0xfe, 0x61, 0x9a, 0xae, 0x2a, 0xfc, 0x3b, 0x79, 0xf2,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xcb, 0x51, 0xac, 0x61, 0x05, 0x00, 0x00,
}

func (x AlgoMethod) String() string {
	s, ok := AlgoMethod_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *AggregationBatch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AggregationBatch)
	if !ok {
		that2, ok := that.(AggregationBatch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RoutingKey != that1.RoutingKey {
		return false
	}
	if this.ConfigHash != that1.ConfigHash {
		return false
	}
	if !bytes.Equal(this.RawConfig, that1.RawConfig) {
		return false
	}
	if len(this.AggregationOpts) != len(that1.AggregationOpts) {
		return false
	}
	for i := range this.AggregationOpts {
		if !this.AggregationOpts[i].Equal(that1.AggregationOpts[i]) {
			return false
		}
	}
	if !this.Points.Equal(that1.Points) {
		return false
	}
	return true
}
func (this *AggregationAlgo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AggregationAlgo)
	if !ok {
		that2, ok := that.(AggregationAlgo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Method != that1.Method {
		return false
	}
	if this.SourceField != that1.SourceField {
		return false
	}
	if this.Window != that1.Window {
		return false
	}
	if that1.Options == nil {
		if this.Options != nil {
			return false
		}
	} else if this.Options == nil {
		return false
	} else if !this.Options.Equal(that1.Options) {
		return false
	}
	if len(this.AddTags) != len(that1.AddTags) {
		return false
	}
	for i := range this.AddTags {
		if this.AddTags[i] != that1.AddTags[i] {
			return false
		}
	}
	return true
}
func (this *AggregationAlgo_HistogramOpts) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AggregationAlgo_HistogramOpts)
	if !ok {
		that2, ok := that.(AggregationAlgo_HistogramOpts)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.HistogramOpts.Equal(that1.HistogramOpts) {
		return false
	}
	return true
}
func (this *AggregationAlgo_ExpoOpts) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AggregationAlgo_ExpoOpts)
	if !ok {
		that2, ok := that.(AggregationAlgo_ExpoOpts)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ExpoOpts.Equal(that1.ExpoOpts) {
		return false
	}
	return true
}
func (this *AggregationAlgo_QuantileOpts) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AggregationAlgo_QuantileOpts)
	if !ok {
		that2, ok := that.(AggregationAlgo_QuantileOpts)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.QuantileOpts.Equal(that1.QuantileOpts) {
		return false
	}
	return true
}
func (this *HistogramOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HistogramOptions)
	if !ok {
		that2, ok := that.(HistogramOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Buckets) != len(that1.Buckets) {
		return false
	}
	for i := range this.Buckets {
		if this.Buckets[i] != that1.Buckets[i] {
			return false
		}
	}
	return true
}
func (this *ExpoHistogramOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExpoHistogramOptions)
	if !ok {
		that2, ok := that.(ExpoHistogramOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxScale != that1.MaxScale {
		return false
	}
	if this.MaxBuckets != that1.MaxBuckets {
		return false
	}
	if this.RecordMinMax != that1.RecordMinMax {
		return false
	}
	return true
}
func (this *QuantileOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QuantileOptions)
	if !ok {
		that2, ok := that.(QuantileOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Percentiles) != len(that1.Percentiles) {
		return false
	}
	for i := range this.Percentiles {
		if this.Percentiles[i] != that1.Percentiles[i] {
			return false
		}
	}
	return true
}
func (this *AggregationBatch) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&aggregate.AggregationBatch{")
	s = append(s, "RoutingKey: "+fmt.Sprintf("%#v", this.RoutingKey)+",\n")
	s = append(s, "ConfigHash: "+fmt.Sprintf("%#v", this.ConfigHash)+",\n")
	s = append(s, "RawConfig: "+fmt.Sprintf("%#v", this.RawConfig)+",\n")
	keysForAggregationOpts := make([]string, 0, len(this.AggregationOpts))
	for k, _ := range this.AggregationOpts {
		keysForAggregationOpts = append(keysForAggregationOpts, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAggregationOpts)
	mapStringForAggregationOpts := "map[string]*AggregationAlgo{"
	for _, k := range keysForAggregationOpts {
		mapStringForAggregationOpts += fmt.Sprintf("%#v: %#v,", k, this.AggregationOpts[k])
	}
	mapStringForAggregationOpts += "}"
	if this.AggregationOpts != nil {
		s = append(s, "AggregationOpts: "+mapStringForAggregationOpts+",\n")
	}
	if this.Points != nil {
		s = append(s, "Points: "+fmt.Sprintf("%#v", this.Points)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AggregationAlgo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&aggregate.AggregationAlgo{")
	s = append(s, "Method: "+fmt.Sprintf("%#v", this.Method)+",\n")
	s = append(s, "SourceField: "+fmt.Sprintf("%#v", this.SourceField)+",\n")
	s = append(s, "Window: "+fmt.Sprintf("%#v", this.Window)+",\n")
	if this.Options != nil {
		s = append(s, "Options: "+fmt.Sprintf("%#v", this.Options)+",\n")
	}
	keysForAddTags := make([]string, 0, len(this.AddTags))
	for k, _ := range this.AddTags {
		keysForAddTags = append(keysForAddTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAddTags)
	mapStringForAddTags := "map[string]string{"
	for _, k := range keysForAddTags {
		mapStringForAddTags += fmt.Sprintf("%#v: %#v,", k, this.AddTags[k])
	}
	mapStringForAddTags += "}"
	if this.AddTags != nil {
		s = append(s, "AddTags: "+mapStringForAddTags+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AggregationAlgo_HistogramOpts) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&aggregate.AggregationAlgo_HistogramOpts{` +
		`HistogramOpts:` + fmt.Sprintf("%#v", this.HistogramOpts) + `}`}, ", ")
	return s
}
func (this *AggregationAlgo_ExpoOpts) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&aggregate.AggregationAlgo_ExpoOpts{` +
		`ExpoOpts:` + fmt.Sprintf("%#v", this.ExpoOpts) + `}`}, ", ")
	return s
}
func (this *AggregationAlgo_QuantileOpts) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&aggregate.AggregationAlgo_QuantileOpts{` +
		`QuantileOpts:` + fmt.Sprintf("%#v", this.QuantileOpts) + `}`}, ", ")
	return s
}
func (this *HistogramOptions) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&aggregate.HistogramOptions{")
	s = append(s, "Buckets: "+fmt.Sprintf("%#v", this.Buckets)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ExpoHistogramOptions) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&aggregate.ExpoHistogramOptions{")
	s = append(s, "MaxScale: "+fmt.Sprintf("%#v", this.MaxScale)+",\n")
	s = append(s, "MaxBuckets: "+fmt.Sprintf("%#v", this.MaxBuckets)+",\n")
	s = append(s, "RecordMinMax: "+fmt.Sprintf("%#v", this.RecordMinMax)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *QuantileOptions) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&aggregate.QuantileOptions{")
	s = append(s, "Percentiles: "+fmt.Sprintf("%#v", this.Percentiles)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringBatch(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *AggregationBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AggregationBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AggregationBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Points != nil {
		{
			size, err := m.Points.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AggregationOpts) > 0 {
		for k := range m.AggregationOpts {
			v := m.AggregationOpts[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintBatch(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintBatch(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintBatch(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RawConfig) > 0 {
		i -= len(m.RawConfig)
		copy(dAtA[i:], m.RawConfig)
		i = encodeVarintBatch(dAtA, i, uint64(len(m.RawConfig)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ConfigHash != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.ConfigHash))
		i--
		dAtA[i] = 0x10
	}
	if m.RoutingKey != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.RoutingKey))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AggregationAlgo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AggregationAlgo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AggregationAlgo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Options != nil {
		{
			size := m.Options.Size()
			i -= size
			if _, err := m.Options.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.AddTags) > 0 {
		for k := range m.AddTags {
			v := m.AddTags[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintBatch(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintBatch(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintBatch(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.Window != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.Window))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SourceField) > 0 {
		i -= len(m.SourceField)
		copy(dAtA[i:], m.SourceField)
		i = encodeVarintBatch(dAtA, i, uint64(len(m.SourceField)))
		i--
		dAtA[i] = 0x12
	}
	if m.Method != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.Method))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AggregationAlgo_HistogramOpts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AggregationAlgo_HistogramOpts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.HistogramOpts != nil {
		{
			size, err := m.HistogramOpts.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	return len(dAtA) - i, nil
}
func (m *AggregationAlgo_ExpoOpts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AggregationAlgo_ExpoOpts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ExpoOpts != nil {
		{
			size, err := m.ExpoOpts.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	return len(dAtA) - i, nil
}
func (m *AggregationAlgo_QuantileOpts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AggregationAlgo_QuantileOpts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.QuantileOpts != nil {
		{
			size, err := m.QuantileOpts.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	return len(dAtA) - i, nil
}
func (m *HistogramOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistogramOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistogramOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Buckets) > 0 {
		for iNdEx := len(m.Buckets) - 1; iNdEx >= 0; iNdEx-- {
			f6 := math.Float64bits(float64(m.Buckets[iNdEx]))
			i -= 8
			encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(f6))
		}
		i = encodeVarintBatch(dAtA, i, uint64(len(m.Buckets)*8))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ExpoHistogramOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExpoHistogramOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExpoHistogramOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecordMinMax {
		i--
		if m.RecordMinMax {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MaxBuckets != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.MaxBuckets))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxScale != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.MaxScale))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QuantileOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuantileOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuantileOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Percentiles) > 0 {
		for iNdEx := len(m.Percentiles) - 1; iNdEx >= 0; iNdEx-- {
			f7 := math.Float64bits(float64(m.Percentiles[iNdEx]))
			i -= 8
			encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(f7))
		}
		i = encodeVarintBatch(dAtA, i, uint64(len(m.Percentiles)*8))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBatch(dAtA []byte, offset int, v uint64) int {
	offset -= sovBatch(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AggregationBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RoutingKey != 0 {
		n += 1 + sovBatch(uint64(m.RoutingKey))
	}
	if m.ConfigHash != 0 {
		n += 1 + sovBatch(uint64(m.ConfigHash))
	}
	l = len(m.RawConfig)
	if l > 0 {
		n += 1 + l + sovBatch(uint64(l))
	}
	if len(m.AggregationOpts) > 0 {
		for k, v := range m.AggregationOpts {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovBatch(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovBatch(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovBatch(uint64(mapEntrySize))
		}
	}
	if m.Points != nil {
		l = m.Points.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	return n
}

func (m *AggregationAlgo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Method != 0 {
		n += 1 + sovBatch(uint64(m.Method))
	}
	l = len(m.SourceField)
	if l > 0 {
		n += 1 + l + sovBatch(uint64(l))
	}
	if m.Window != 0 {
		n += 1 + sovBatch(uint64(m.Window))
	}
	if len(m.AddTags) > 0 {
		for k, v := range m.AddTags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovBatch(uint64(len(k))) + 1 + len(v) + sovBatch(uint64(len(v)))
			n += mapEntrySize + 1 + sovBatch(uint64(mapEntrySize))
		}
	}
	if m.Options != nil {
		n += m.Options.Size()
	}
	return n
}

func (m *AggregationAlgo_HistogramOpts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HistogramOpts != nil {
		l = m.HistogramOpts.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	return n
}
func (m *AggregationAlgo_ExpoOpts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExpoOpts != nil {
		l = m.ExpoOpts.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	return n
}
func (m *AggregationAlgo_QuantileOpts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.QuantileOpts != nil {
		l = m.QuantileOpts.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	return n
}
func (m *HistogramOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Buckets) > 0 {
		n += 1 + sovBatch(uint64(len(m.Buckets)*8)) + len(m.Buckets)*8
	}
	return n
}

func (m *ExpoHistogramOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxScale != 0 {
		n += 1 + sovBatch(uint64(m.MaxScale))
	}
	if m.MaxBuckets != 0 {
		n += 1 + sovBatch(uint64(m.MaxBuckets))
	}
	if m.RecordMinMax {
		n += 2
	}
	return n
}

func (m *QuantileOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Percentiles) > 0 {
		n += 1 + sovBatch(uint64(len(m.Percentiles)*8)) + len(m.Percentiles)*8
	}
	return n
}

func sovBatch(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBatch(x uint64) (n int) {
	return sovBatch(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AggregationBatch) String() string {
	if this == nil {
		return "nil"
	}
	keysForAggregationOpts := make([]string, 0, len(this.AggregationOpts))
	for k, _ := range this.AggregationOpts {
		keysForAggregationOpts = append(keysForAggregationOpts, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAggregationOpts)
	mapStringForAggregationOpts := "map[string]*AggregationAlgo{"
	for _, k := range keysForAggregationOpts {
		mapStringForAggregationOpts += fmt.Sprintf("%v: %v,", k, this.AggregationOpts[k])
	}
	mapStringForAggregationOpts += "}"
	s := strings.Join([]string{`&AggregationBatch{`,
		`RoutingKey:` + fmt.Sprintf("%v", this.RoutingKey) + `,`,
		`ConfigHash:` + fmt.Sprintf("%v", this.ConfigHash) + `,`,
		`RawConfig:` + fmt.Sprintf("%v", this.RawConfig) + `,`,
		`AggregationOpts:` + mapStringForAggregationOpts + `,`,
		`Points:` + strings.Replace(fmt.Sprintf("%v", this.Points), "PBPoints", "point.PBPoints", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AggregationAlgo) String() string {
	if this == nil {
		return "nil"
	}
	keysForAddTags := make([]string, 0, len(this.AddTags))
	for k, _ := range this.AddTags {
		keysForAddTags = append(keysForAddTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAddTags)
	mapStringForAddTags := "map[string]string{"
	for _, k := range keysForAddTags {
		mapStringForAddTags += fmt.Sprintf("%v: %v,", k, this.AddTags[k])
	}
	mapStringForAddTags += "}"
	s := strings.Join([]string{`&AggregationAlgo{`,
		`Method:` + fmt.Sprintf("%v", this.Method) + `,`,
		`SourceField:` + fmt.Sprintf("%v", this.SourceField) + `,`,
		`Window:` + fmt.Sprintf("%v", this.Window) + `,`,
		`AddTags:` + mapStringForAddTags + `,`,
		`Options:` + fmt.Sprintf("%v", this.Options) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AggregationAlgo_HistogramOpts) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AggregationAlgo_HistogramOpts{`,
		`HistogramOpts:` + strings.Replace(fmt.Sprintf("%v", this.HistogramOpts), "HistogramOptions", "HistogramOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AggregationAlgo_ExpoOpts) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AggregationAlgo_ExpoOpts{`,
		`ExpoOpts:` + strings.Replace(fmt.Sprintf("%v", this.ExpoOpts), "ExpoHistogramOptions", "ExpoHistogramOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AggregationAlgo_QuantileOpts) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AggregationAlgo_QuantileOpts{`,
		`QuantileOpts:` + strings.Replace(fmt.Sprintf("%v", this.QuantileOpts), "QuantileOptions", "QuantileOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *HistogramOptions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HistogramOptions{`,
		`Buckets:` + fmt.Sprintf("%v", this.Buckets) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ExpoHistogramOptions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ExpoHistogramOptions{`,
		`MaxScale:` + fmt.Sprintf("%v", this.MaxScale) + `,`,
		`MaxBuckets:` + fmt.Sprintf("%v", this.MaxBuckets) + `,`,
		`RecordMinMax:` + fmt.Sprintf("%v", this.RecordMinMax) + `,`,
		`}`,
	}, "")
	return s
}
func (this *QuantileOptions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&QuantileOptions{`,
		`Percentiles:` + fmt.Sprintf("%v", this.Percentiles) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringBatch(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *AggregationBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AggregationBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AggregationBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingKey", wireType)
			}
			m.RoutingKey = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoutingKey |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigHash", wireType)
			}
			m.ConfigHash = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfigHash |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawConfig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawConfig = append(m.RawConfig[:0], dAtA[iNdEx:postIndex]...)
			if m.RawConfig == nil {
				m.RawConfig = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationOpts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AggregationOpts == nil {
				m.AggregationOpts = make(map[string]*AggregationAlgo)
			}
			var mapkey string
			var mapvalue *AggregationAlgo
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBatch
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBatch
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthBatch
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthBatch
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBatch
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthBatch
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthBatch
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &AggregationAlgo{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipBatch(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthBatch
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AggregationOpts[mapkey] = mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Points", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Points == nil {
				m.Points = &point.PBPoints{}
			}
			if err := m.Points.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AggregationAlgo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AggregationAlgo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AggregationAlgo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			m.Method = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Method |= AlgoMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceField", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceField = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Window", wireType)
			}
			m.Window = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Window |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddTags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AddTags == nil {
				m.AddTags = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBatch
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBatch
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthBatch
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthBatch
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBatch
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthBatch
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthBatch
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipBatch(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthBatch
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AddTags[mapkey] = mapvalue
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistogramOpts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &HistogramOptions{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Options = &AggregationAlgo_HistogramOpts{v}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpoOpts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ExpoHistogramOptions{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Options = &AggregationAlgo_ExpoOpts{v}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuantileOpts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &QuantileOptions{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Options = &AggregationAlgo_QuantileOpts{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HistogramOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistogramOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistogramOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
				iNdEx += 8
				v2 := float64(math.Float64frombits(v))
				m.Buckets = append(m.Buckets, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBatch
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthBatch
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthBatch
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen / 8
				if elementCount != 0 && len(m.Buckets) == 0 {
					m.Buckets = make([]float64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
					iNdEx += 8
					v2 := float64(math.Float64frombits(v))
					m.Buckets = append(m.Buckets, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Buckets", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBatch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExpoHistogramOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExpoHistogramOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExpoHistogramOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxScale", wireType)
			}
			m.MaxScale = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxScale |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBuckets", wireType)
			}
			m.MaxBuckets = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBuckets |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordMinMax", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RecordMinMax = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBatch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuantileOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuantileOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuantileOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
				iNdEx += 8
				v2 := float64(math.Float64frombits(v))
				m.Percentiles = append(m.Percentiles, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBatch
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthBatch
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthBatch
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen / 8
				if elementCount != 0 && len(m.Percentiles) == 0 {
					m.Percentiles = make([]float64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
					iNdEx += 8
					v2 := float64(math.Float64frombits(v))
					m.Percentiles = append(m.Percentiles, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Percentiles", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBatch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBatch(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBatch
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBatch
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBatch
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBatch        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBatch          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBatch = fmt.Errorf("proto: unexpected end of group")
)
