// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aggregate/tracedata.proto

package aggregate

import (
	fmt "fmt"
	point "github.com/GuanceCloud/cliutils/point"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TraceDataPacket struct {
	TraceIdHash uint64 `protobuf:"varint,1,opt,name=trace_id_hash,json=traceIdHash,proto3" json:"trace_id_hash,omitempty"`
	RawTraceId  string `protobuf:"bytes,2,opt,name=raw_trace_id,json=rawTraceId,proto3" json:"raw_trace_id,omitempty"`
	Token       string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Source      string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// version
	ConfigVersion int64            `protobuf:"varint,5,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	HasError      bool             `protobuf:"varint,6,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	Spans         []*point.PBPoint `protobuf:"bytes,8,rep,name=spans,proto3" json:"spans,omitempty"`
}

func (m *TraceDataPacket) Reset()      { *m = TraceDataPacket{} }
func (*TraceDataPacket) ProtoMessage() {}
func (*TraceDataPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_2852b5267f70864e, []int{0}
}
func (m *TraceDataPacket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TraceDataPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TraceDataPacket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TraceDataPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceDataPacket.Merge(m, src)
}
func (m *TraceDataPacket) XXX_Size() int {
	return m.Size()
}
func (m *TraceDataPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceDataPacket.DiscardUnknown(m)
}

var xxx_messageInfo_TraceDataPacket proto.InternalMessageInfo

func (m *TraceDataPacket) GetTraceIdHash() uint64 {
	if m != nil {
		return m.TraceIdHash
	}
	return 0
}

func (m *TraceDataPacket) GetRawTraceId() string {
	if m != nil {
		return m.RawTraceId
	}
	return ""
}

func (m *TraceDataPacket) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TraceDataPacket) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TraceDataPacket) GetConfigVersion() int64 {
	if m != nil {
		return m.ConfigVersion
	}
	return 0
}

func (m *TraceDataPacket) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *TraceDataPacket) GetSpans() []*point.PBPoint {
	if m != nil {
		return m.Spans
	}
	return nil
}

// batch packages
type TraceBatch struct {
	CollectorId string             `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Packets     []*TraceDataPacket `protobuf:"bytes,2,rep,name=packets,proto3" json:"packets,omitempty"`
}

func (m *TraceBatch) Reset()      { *m = TraceBatch{} }
func (*TraceBatch) ProtoMessage() {}
func (*TraceBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_2852b5267f70864e, []int{1}
}
func (m *TraceBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TraceBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TraceBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TraceBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceBatch.Merge(m, src)
}
func (m *TraceBatch) XXX_Size() int {
	return m.Size()
}
func (m *TraceBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceBatch.DiscardUnknown(m)
}

var xxx_messageInfo_TraceBatch proto.InternalMessageInfo

func (m *TraceBatch) GetCollectorId() string {
	if m != nil {
		return m.CollectorId
	}
	return ""
}

func (m *TraceBatch) GetPackets() []*TraceDataPacket {
	if m != nil {
		return m.Packets
	}
	return nil
}

func init() {
	proto.RegisterType((*TraceDataPacket)(nil), "aggregate.v1.TraceDataPacket")
	proto.RegisterType((*TraceBatch)(nil), "aggregate.v1.TraceBatch")
}

func init() { proto.RegisterFile("aggregate/tracedata.proto", fileDescriptor_2852b5267f70864e) }

var fileDescriptor_2852b5267f70864e = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xbb, 0x6e, 0xdb, 0x30,
	0x14, 0x15, 0xfd, 0xaa, 0x4d, 0xd9, 0x2e, 0x4a, 0x14, 0x05, 0xdb, 0xa2, 0x84, 0x6a, 0xb4, 0x80,
	0x26, 0x19, 0x6d, 0x86, 0x0c, 0x99, 0x62, 0x24, 0x40, 0xbc, 0x19, 0x82, 0x91, 0x21, 0x8b, 0x70,
	0x23, 0x31, 0x92, 0x60, 0x43, 0x14, 0x48, 0xc6, 0x5e, 0xf3, 0x09, 0xf9, 0x8c, 0x7c, 0x4a, 0x46,
	0x8f, 0x1e, 0x63, 0x79, 0xc9, 0x16, 0x7f, 0x42, 0x20, 0x2a, 0x36, 0x82, 0x2c, 0x24, 0xce, 0x83,
	0x07, 0xf7, 0x1e, 0xe2, 0xef, 0x10, 0xc7, 0x92, 0xc7, 0xa0, 0xf9, 0x50, 0x4b, 0x08, 0x79, 0x04,
	0x1a, 0xbc, 0x5c, 0x0a, 0x2d, 0x48, 0xf7, 0x20, 0x79, 0x8b, 0x7f, 0x3f, 0xbe, 0xe4, 0x22, 0xcd,
	0xf4, 0xd0, 0x9c, 0x95, 0x61, 0xf0, 0x82, 0xf0, 0xe7, 0x69, 0xf9, 0xe8, 0x0c, 0x34, 0x4c, 0x20,
	0x9c, 0x71, 0x4d, 0x06, 0xb8, 0x67, 0x72, 0x82, 0x34, 0x0a, 0x12, 0x50, 0x09, 0x45, 0x0e, 0x72,
	0x1b, 0xbe, 0x6d, 0xc8, 0x71, 0x74, 0x01, 0x2a, 0x21, 0x0e, 0xee, 0x4a, 0x58, 0x06, 0x7b, 0x1f,
	0xad, 0x39, 0xc8, 0xed, 0xf8, 0x58, 0xc2, 0x72, 0x5a, 0xb9, 0xc8, 0x57, 0xdc, 0xd4, 0x62, 0xc6,
	0x33, 0x5a, 0x37, 0x52, 0x05, 0xc8, 0x37, 0xdc, 0x52, 0xe2, 0x56, 0x86, 0x9c, 0x36, 0x0c, 0xfd,
	0x86, 0xc8, 0x5f, 0xdc, 0x0f, 0x45, 0x76, 0x93, 0xc6, 0xc1, 0x82, 0x4b, 0x95, 0x8a, 0x8c, 0x36,
	0x1d, 0xe4, 0xd6, 0xfd, 0x5e, 0xc5, 0x5e, 0x56, 0x24, 0xf9, 0x89, 0x3b, 0x09, 0xa8, 0x80, 0x4b,
	0x29, 0x24, 0x6d, 0x39, 0xc8, 0x6d, 0xfb, 0xed, 0x04, 0xd4, 0x79, 0x89, 0xc9, 0x1f, 0xdc, 0x54,
	0x39, 0x64, 0x8a, 0xb6, 0x9d, 0xba, 0x6b, 0xff, 0xef, 0x7b, 0xd5, 0xa2, 0x93, 0xd1, 0xa4, 0xbc,
	0xfd, 0x4a, 0x1c, 0x24, 0x18, 0x9b, 0x11, 0x47, 0xa0, 0xc3, 0x84, 0xfc, 0xc6, 0xdd, 0x50, 0xcc,
	0xe7, 0x3c, 0xd4, 0x42, 0x96, 0x7b, 0x20, 0x33, 0x95, 0x7d, 0xe0, 0xc6, 0x11, 0x39, 0xc6, 0x9f,
	0x72, 0x53, 0x8c, 0xa2, 0x35, 0x13, 0xfc, 0xcb, 0x7b, 0xdf, 0xaa, 0xf7, 0xa1, 0x3e, 0x7f, 0xef,
	0x1e, 0x9d, 0xae, 0x36, 0xcc, 0x5a, 0x6f, 0x98, 0xb5, 0xdb, 0x30, 0x74, 0x57, 0x30, 0xf4, 0x50,
	0x30, 0xf4, 0x58, 0x30, 0xb4, 0x2a, 0x18, 0x7a, 0x2a, 0x18, 0x7a, 0x2e, 0x98, 0xb5, 0x2b, 0x18,
	0xba, 0xdf, 0x32, 0x6b, 0xb5, 0x65, 0xd6, 0x7a, 0xcb, 0xac, 0x2b, 0x7b, 0x78, 0x72, 0x88, 0xbf,
	0x6e, 0x99, 0x5f, 0x3a, 0x7a, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x97, 0xca, 0x87, 0x48, 0xe3, 0x01,
	0x00, 0x00,
}

func (this *TraceDataPacket) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TraceDataPacket)
	if !ok {
		that2, ok := that.(TraceDataPacket)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TraceIdHash != that1.TraceIdHash {
		return false
	}
	if this.RawTraceId != that1.RawTraceId {
		return false
	}
	if this.Token != that1.Token {
		return false
	}
	if this.Source != that1.Source {
		return false
	}
	if this.ConfigVersion != that1.ConfigVersion {
		return false
	}
	if this.HasError != that1.HasError {
		return false
	}
	if len(this.Spans) != len(that1.Spans) {
		return false
	}
	for i := range this.Spans {
		if !this.Spans[i].Equal(that1.Spans[i]) {
			return false
		}
	}
	return true
}
func (this *TraceBatch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TraceBatch)
	if !ok {
		that2, ok := that.(TraceBatch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CollectorId != that1.CollectorId {
		return false
	}
	if len(this.Packets) != len(that1.Packets) {
		return false
	}
	for i := range this.Packets {
		if !this.Packets[i].Equal(that1.Packets[i]) {
			return false
		}
	}
	return true
}
func (this *TraceDataPacket) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&aggregate.TraceDataPacket{")
	s = append(s, "TraceIdHash: "+fmt.Sprintf("%#v", this.TraceIdHash)+",\n")
	s = append(s, "RawTraceId: "+fmt.Sprintf("%#v", this.RawTraceId)+",\n")
	s = append(s, "Token: "+fmt.Sprintf("%#v", this.Token)+",\n")
	s = append(s, "Source: "+fmt.Sprintf("%#v", this.Source)+",\n")
	s = append(s, "ConfigVersion: "+fmt.Sprintf("%#v", this.ConfigVersion)+",\n")
	s = append(s, "HasError: "+fmt.Sprintf("%#v", this.HasError)+",\n")
	if this.Spans != nil {
		s = append(s, "Spans: "+fmt.Sprintf("%#v", this.Spans)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TraceBatch) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&aggregate.TraceBatch{")
	s = append(s, "CollectorId: "+fmt.Sprintf("%#v", this.CollectorId)+",\n")
	if this.Packets != nil {
		s = append(s, "Packets: "+fmt.Sprintf("%#v", this.Packets)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTracedata(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TraceDataPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TraceDataPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TraceDataPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Spans) > 0 {
		for iNdEx := len(m.Spans) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Spans[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTracedata(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.HasError {
		i--
		if m.HasError {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.ConfigVersion != 0 {
		i = encodeVarintTracedata(dAtA, i, uint64(m.ConfigVersion))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTracedata(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintTracedata(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RawTraceId) > 0 {
		i -= len(m.RawTraceId)
		copy(dAtA[i:], m.RawTraceId)
		i = encodeVarintTracedata(dAtA, i, uint64(len(m.RawTraceId)))
		i--
		dAtA[i] = 0x12
	}
	if m.TraceIdHash != 0 {
		i = encodeVarintTracedata(dAtA, i, uint64(m.TraceIdHash))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TraceBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TraceBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TraceBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Packets) > 0 {
		for iNdEx := len(m.Packets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Packets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTracedata(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CollectorId) > 0 {
		i -= len(m.CollectorId)
		copy(dAtA[i:], m.CollectorId)
		i = encodeVarintTracedata(dAtA, i, uint64(len(m.CollectorId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTracedata(dAtA []byte, offset int, v uint64) int {
	offset -= sovTracedata(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TraceDataPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TraceIdHash != 0 {
		n += 1 + sovTracedata(uint64(m.TraceIdHash))
	}
	l = len(m.RawTraceId)
	if l > 0 {
		n += 1 + l + sovTracedata(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovTracedata(uint64(l))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTracedata(uint64(l))
	}
	if m.ConfigVersion != 0 {
		n += 1 + sovTracedata(uint64(m.ConfigVersion))
	}
	if m.HasError {
		n += 2
	}
	if len(m.Spans) > 0 {
		for _, e := range m.Spans {
			l = e.Size()
			n += 1 + l + sovTracedata(uint64(l))
		}
	}
	return n
}

func (m *TraceBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CollectorId)
	if l > 0 {
		n += 1 + l + sovTracedata(uint64(l))
	}
	if len(m.Packets) > 0 {
		for _, e := range m.Packets {
			l = e.Size()
			n += 1 + l + sovTracedata(uint64(l))
		}
	}
	return n
}

func sovTracedata(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTracedata(x uint64) (n int) {
	return sovTracedata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TraceDataPacket) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForSpans := "[]*PBPoint{"
	for _, f := range this.Spans {
		repeatedStringForSpans += strings.Replace(fmt.Sprintf("%v", f), "PBPoint", "point.PBPoint", 1) + ","
	}
	repeatedStringForSpans += "}"
	s := strings.Join([]string{`&TraceDataPacket{`,
		`TraceIdHash:` + fmt.Sprintf("%v", this.TraceIdHash) + `,`,
		`RawTraceId:` + fmt.Sprintf("%v", this.RawTraceId) + `,`,
		`Token:` + fmt.Sprintf("%v", this.Token) + `,`,
		`Source:` + fmt.Sprintf("%v", this.Source) + `,`,
		`ConfigVersion:` + fmt.Sprintf("%v", this.ConfigVersion) + `,`,
		`HasError:` + fmt.Sprintf("%v", this.HasError) + `,`,
		`Spans:` + repeatedStringForSpans + `,`,
		`}`,
	}, "")
	return s
}
func (this *TraceBatch) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForPackets := "[]*TraceDataPacket{"
	for _, f := range this.Packets {
		repeatedStringForPackets += strings.Replace(f.String(), "TraceDataPacket", "TraceDataPacket", 1) + ","
	}
	repeatedStringForPackets += "}"
	s := strings.Join([]string{`&TraceBatch{`,
		`CollectorId:` + fmt.Sprintf("%v", this.CollectorId) + `,`,
		`Packets:` + repeatedStringForPackets + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTracedata(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TraceDataPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTracedata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TraceDataPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TraceDataPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceIdHash", wireType)
			}
			m.TraceIdHash = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceIdHash |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawTraceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracedata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawTraceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracedata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracedata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigVersion", wireType)
			}
			m.ConfigVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfigVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasError", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasError = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTracedata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTracedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spans = append(m.Spans, &point.PBPoint{})
			if err := m.Spans[len(m.Spans)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTracedata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTracedata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TraceBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTracedata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TraceBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TraceBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracedata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Packets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTracedata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTracedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Packets = append(m.Packets, &TraceDataPacket{})
			if err := m.Packets[len(m.Packets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTracedata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTracedata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTracedata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTracedata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTracedata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTracedata
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTracedata
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTracedata
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTracedata        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTracedata          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTracedata = fmt.Errorf("proto: unexpected end of group")
)
