// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aggregate/tsdata.proto

package aggregate

import (
	bytes "bytes"
	fmt "fmt"
	point "github.com/GuanceCloud/cliutils/point"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 通用数据包，适用于所有数据类型
type DataPacket struct {
	GroupIdHash uint64 `protobuf:"varint,1,opt,name=group_id_hash,json=groupIdHash,proto3" json:"group_id_hash,omitempty"`
	RawGroupId  string `protobuf:"bytes,2,opt,name=raw_group_id,json=rawGroupId,proto3" json:"raw_group_id,omitempty"`
	Token       string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Source      string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	DataType    string `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	// version
	ConfigVersion int64 `protobuf:"varint,6,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	HasError      bool  `protobuf:"varint,7,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	// 新增：分组键名称
	GroupKey string `protobuf:"bytes,8,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// 新增：数据点数量统计
	PointCount int32 `protobuf:"varint,9,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	// 新增：时间范围
	TraceStartTimeUnixNano int64            `protobuf:"varint,10,opt,name=trace_start_time_unix_nano,json=traceStartTimeUnixNano,proto3" json:"trace_start_time_unix_nano,omitempty"`
	TraceEndTimeUnixNano   int64            `protobuf:"varint,11,opt,name=trace_end_time_unix_nano,json=traceEndTimeUnixNano,proto3" json:"trace_end_time_unix_nano,omitempty"`
	Points                 []*point.PBPoint `protobuf:"bytes,12,rep,name=points,proto3" json:"points,omitempty"`
}

func (m *DataPacket) Reset()      { *m = DataPacket{} }
func (*DataPacket) ProtoMessage() {}
func (*DataPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d8a8f10bff5a13, []int{0}
}
func (m *DataPacket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataPacket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPacket.Merge(m, src)
}
func (m *DataPacket) XXX_Size() int {
	return m.Size()
}
func (m *DataPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPacket.DiscardUnknown(m)
}

var xxx_messageInfo_DataPacket proto.InternalMessageInfo

func (m *DataPacket) GetGroupIdHash() uint64 {
	if m != nil {
		return m.GroupIdHash
	}
	return 0
}

func (m *DataPacket) GetRawGroupId() string {
	if m != nil {
		return m.RawGroupId
	}
	return ""
}

func (m *DataPacket) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DataPacket) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *DataPacket) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *DataPacket) GetConfigVersion() int64 {
	if m != nil {
		return m.ConfigVersion
	}
	return 0
}

func (m *DataPacket) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *DataPacket) GetGroupKey() string {
	if m != nil {
		return m.GroupKey
	}
	return ""
}

func (m *DataPacket) GetPointCount() int32 {
	if m != nil {
		return m.PointCount
	}
	return 0
}

func (m *DataPacket) GetTraceStartTimeUnixNano() int64 {
	if m != nil {
		return m.TraceStartTimeUnixNano
	}
	return 0
}

func (m *DataPacket) GetTraceEndTimeUnixNano() int64 {
	if m != nil {
		return m.TraceEndTimeUnixNano
	}
	return 0
}

func (m *DataPacket) GetPoints() []*point.PBPoint {
	if m != nil {
		return m.Points
	}
	return nil
}

// V2 数据包：不在解码阶段展开 point.PBPoint，减少常驻对象数量。
type DataPacketV2 struct {
	GroupIdHash            uint64   `protobuf:"varint,1,opt,name=group_id_hash,json=groupIdHash,proto3" json:"group_id_hash,omitempty"`
	RawGroupId             string   `protobuf:"bytes,2,opt,name=raw_group_id,json=rawGroupId,proto3" json:"raw_group_id,omitempty"`
	Token                  string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Source                 string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	DataType               string   `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	ConfigVersion          int64    `protobuf:"varint,6,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	HasError               bool     `protobuf:"varint,7,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	GroupKey               string   `protobuf:"bytes,8,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	PointCount             int32    `protobuf:"varint,9,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	TraceStartTimeUnixNano int64    `protobuf:"varint,10,opt,name=trace_start_time_unix_nano,json=traceStartTimeUnixNano,proto3" json:"trace_start_time_unix_nano,omitempty"`
	TraceEndTimeUnixNano   int64    `protobuf:"varint,11,opt,name=trace_end_time_unix_nano,json=traceEndTimeUnixNano,proto3" json:"trace_end_time_unix_nano,omitempty"`
	RawPoints              [][]byte `protobuf:"bytes,12,rep,name=raw_points,json=rawPoints,proto3" json:"raw_points,omitempty"`
}

func (m *DataPacketV2) Reset()      { *m = DataPacketV2{} }
func (*DataPacketV2) ProtoMessage() {}
func (*DataPacketV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d8a8f10bff5a13, []int{1}
}
func (m *DataPacketV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataPacketV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataPacketV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataPacketV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPacketV2.Merge(m, src)
}
func (m *DataPacketV2) XXX_Size() int {
	return m.Size()
}
func (m *DataPacketV2) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPacketV2.DiscardUnknown(m)
}

var xxx_messageInfo_DataPacketV2 proto.InternalMessageInfo

func (m *DataPacketV2) GetGroupIdHash() uint64 {
	if m != nil {
		return m.GroupIdHash
	}
	return 0
}

func (m *DataPacketV2) GetRawGroupId() string {
	if m != nil {
		return m.RawGroupId
	}
	return ""
}

func (m *DataPacketV2) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DataPacketV2) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *DataPacketV2) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *DataPacketV2) GetConfigVersion() int64 {
	if m != nil {
		return m.ConfigVersion
	}
	return 0
}

func (m *DataPacketV2) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *DataPacketV2) GetGroupKey() string {
	if m != nil {
		return m.GroupKey
	}
	return ""
}

func (m *DataPacketV2) GetPointCount() int32 {
	if m != nil {
		return m.PointCount
	}
	return 0
}

func (m *DataPacketV2) GetTraceStartTimeUnixNano() int64 {
	if m != nil {
		return m.TraceStartTimeUnixNano
	}
	return 0
}

func (m *DataPacketV2) GetTraceEndTimeUnixNano() int64 {
	if m != nil {
		return m.TraceEndTimeUnixNano
	}
	return 0
}

func (m *DataPacketV2) GetRawPoints() [][]byte {
	if m != nil {
		return m.RawPoints
	}
	return nil
}

// batch packages
type DataBatch struct {
	CollectorId string        `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Packets     []*DataPacket `protobuf:"bytes,2,rep,name=packets,proto3" json:"packets,omitempty"`
}

func (m *DataBatch) Reset()      { *m = DataBatch{} }
func (*DataBatch) ProtoMessage() {}
func (*DataBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d8a8f10bff5a13, []int{2}
}
func (m *DataBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataBatch.Merge(m, src)
}
func (m *DataBatch) XXX_Size() int {
	return m.Size()
}
func (m *DataBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_DataBatch.DiscardUnknown(m)
}

var xxx_messageInfo_DataBatch proto.InternalMessageInfo

func (m *DataBatch) GetCollectorId() string {
	if m != nil {
		return m.CollectorId
	}
	return ""
}

func (m *DataBatch) GetPackets() []*DataPacket {
	if m != nil {
		return m.Packets
	}
	return nil
}

type DataBatchV2 struct {
	CollectorId string          `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Packets     []*DataPacketV2 `protobuf:"bytes,2,rep,name=packets,proto3" json:"packets,omitempty"`
}

func (m *DataBatchV2) Reset()      { *m = DataBatchV2{} }
func (*DataBatchV2) ProtoMessage() {}
func (*DataBatchV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d8a8f10bff5a13, []int{3}
}
func (m *DataBatchV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataBatchV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataBatchV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataBatchV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataBatchV2.Merge(m, src)
}
func (m *DataBatchV2) XXX_Size() int {
	return m.Size()
}
func (m *DataBatchV2) XXX_DiscardUnknown() {
	xxx_messageInfo_DataBatchV2.DiscardUnknown(m)
}

var xxx_messageInfo_DataBatchV2 proto.InternalMessageInfo

func (m *DataBatchV2) GetCollectorId() string {
	if m != nil {
		return m.CollectorId
	}
	return ""
}

func (m *DataBatchV2) GetPackets() []*DataPacketV2 {
	if m != nil {
		return m.Packets
	}
	return nil
}

func init() {
	proto.RegisterType((*DataPacket)(nil), "aggregate.v1.DataPacket")
	proto.RegisterType((*DataPacketV2)(nil), "aggregate.v1.DataPacketV2")
	proto.RegisterType((*DataBatch)(nil), "aggregate.v1.DataBatch")
	proto.RegisterType((*DataBatchV2)(nil), "aggregate.v1.DataBatchV2")
}

func init() { proto.RegisterFile("aggregate/tsdata.proto", fileDescriptor_73d8a8f10bff5a13) }

var fileDescriptor_73d8a8f10bff5a13 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0x41, 0x6f, 0xd3, 0x3c,
	0x18, 0x8e, 0xd7, 0xad, 0x6b, 0xdf, 0x64, 0x93, 0x3e, 0x6b, 0x9a, 0xac, 0x7e, 0xc2, 0x84, 0x4a,
	0xa0, 0x9c, 0x5a, 0x51, 0x10, 0x07, 0x38, 0x51, 0x98, 0x60, 0x42, 0x42, 0x55, 0x18, 0x3d, 0x70,
	0xb1, 0xbc, 0xc4, 0x6b, 0xa2, 0x6e, 0x76, 0xe4, 0xb8, 0xeb, 0x7a, 0xe3, 0x27, 0xf0, 0x33, 0xf8,
	0x01, 0xdc, 0xf8, 0x03, 0x1c, 0x7b, 0xdc, 0x91, 0xa6, 0x17, 0x8e, 0xfb, 0x09, 0x28, 0xce, 0xd6,
	0x8d, 0x49, 0x48, 0x1c, 0x39, 0x70, 0x49, 0xf4, 0x3e, 0xcf, 0xf3, 0xfa, 0x79, 0xe3, 0xc7, 0x31,
	0xec, 0xf2, 0xd1, 0x48, 0x8b, 0x11, 0x37, 0xa2, 0x6b, 0xf2, 0x98, 0x1b, 0xde, 0xc9, 0xb4, 0x32,
	0x0a, 0x7b, 0x2b, 0xbc, 0x73, 0xfa, 0xb0, 0xf5, 0x5f, 0xa6, 0x52, 0x69, 0xba, 0xf6, 0x59, 0x09,
	0xda, 0x5f, 0x6b, 0x00, 0x2f, 0xb9, 0xe1, 0x03, 0x1e, 0x8d, 0x85, 0xc1, 0x6d, 0xd8, 0x1a, 0x69,
	0x35, 0xc9, 0x58, 0x1a, 0xb3, 0x84, 0xe7, 0x09, 0x41, 0x3e, 0x0a, 0xd6, 0x43, 0xd7, 0x82, 0xfb,
	0xf1, 0x6b, 0x9e, 0x27, 0xd8, 0x07, 0x4f, 0xf3, 0x29, 0xbb, 0xd2, 0x91, 0x35, 0x1f, 0x05, 0xcd,
	0x10, 0x34, 0x9f, 0xbe, 0xaa, 0x54, 0x78, 0x07, 0x36, 0x8c, 0x1a, 0x0b, 0x49, 0x6a, 0x96, 0xaa,
	0x0a, 0xbc, 0x0b, 0xf5, 0x5c, 0x4d, 0x74, 0x24, 0xc8, 0xba, 0x85, 0x2f, 0x2b, 0xfc, 0x3f, 0x34,
	0xcb, 0x89, 0x99, 0x99, 0x65, 0x82, 0x6c, 0x58, 0xaa, 0x51, 0x02, 0x07, 0xb3, 0x4c, 0xe0, 0xfb,
	0xb0, 0x1d, 0x29, 0x79, 0x94, 0x8e, 0xd8, 0xa9, 0xd0, 0x79, 0xaa, 0x24, 0xa9, 0xfb, 0x28, 0xa8,
	0x85, 0x5b, 0x15, 0x3a, 0xac, 0xc0, 0x72, 0x8d, 0x84, 0xe7, 0x4c, 0x68, 0xad, 0x34, 0xd9, 0xf4,
	0x51, 0xd0, 0x08, 0x1b, 0x09, 0xcf, 0xf7, 0xca, 0xba, 0x24, 0xab, 0x61, 0xc7, 0x62, 0x46, 0x1a,
	0x95, 0x81, 0x05, 0xde, 0x88, 0x19, 0xbe, 0x0b, 0xae, 0xdd, 0x0f, 0x16, 0xa9, 0x89, 0x34, 0xa4,
	0xe9, 0xa3, 0x60, 0x23, 0x04, 0x0b, 0xbd, 0x28, 0x11, 0xfc, 0x14, 0x5a, 0x46, 0xf3, 0x48, 0xb0,
	0xdc, 0x70, 0x6d, 0x98, 0x49, 0x4f, 0x04, 0x9b, 0xc8, 0xf4, 0x8c, 0x49, 0x2e, 0x15, 0x01, 0x3b,
	0xcd, 0xae, 0x55, 0xbc, 0x2b, 0x05, 0x07, 0xe9, 0x89, 0x78, 0x2f, 0xd3, 0xb3, 0xb7, 0x5c, 0x2a,
	0xfc, 0x04, 0x48, 0xd5, 0x2b, 0x64, 0x7c, 0xbb, 0xd3, 0xb5, 0x9d, 0x3b, 0x96, 0xdf, 0x93, 0xf1,
	0x2f, 0x7d, 0x0f, 0xa0, 0x6e, 0x27, 0xc8, 0x89, 0xe7, 0xd7, 0x02, 0xb7, 0xb7, 0xdd, 0xa9, 0x32,
	0x1b, 0xf4, 0x07, 0xe5, 0x3b, 0xbc, 0x64, 0xdb, 0x5f, 0x6a, 0xe0, 0x5d, 0xa7, 0x37, 0xec, 0xfd,
	0xcb, 0xef, 0xef, 0xc8, 0xef, 0x0e, 0x94, 0xdb, 0xc9, 0x6e, 0x64, 0xe8, 0x85, 0x4d, 0xcd, 0xa7,
	0x83, 0x2a, 0xb6, 0x43, 0x68, 0x96, 0xa9, 0xf5, 0xb9, 0x89, 0x12, 0x7c, 0x0f, 0xbc, 0x48, 0x1d,
	0x1f, 0x8b, 0xc8, 0x28, 0x5d, 0xc6, 0x81, 0xec, 0x07, 0xba, 0x2b, 0x6c, 0x3f, 0xc6, 0x3d, 0xd8,
	0xcc, 0x6c, 0xc2, 0x39, 0x59, 0xb3, 0xe7, 0x81, 0x74, 0x6e, 0xfe, 0xd7, 0x9d, 0xeb, 0x23, 0x10,
	0x5e, 0x09, 0xdb, 0x47, 0xe0, 0xae, 0x3c, 0x86, 0xbd, 0x3f, 0x71, 0x79, 0x7c, 0xdb, 0xa5, 0xf5,
	0x3b, 0x97, 0x61, 0x6f, 0xe5, 0xd3, 0x7f, 0x3e, 0x5f, 0x50, 0xe7, 0x7c, 0x41, 0x9d, 0x8b, 0x05,
	0x45, 0x1f, 0x0b, 0x8a, 0x3e, 0x17, 0x14, 0x7d, 0x2b, 0x28, 0x9a, 0x17, 0x14, 0x7d, 0x2f, 0x28,
	0xfa, 0x51, 0x50, 0xe7, 0xa2, 0xa0, 0xe8, 0xd3, 0x92, 0x3a, 0xf3, 0x25, 0x75, 0xce, 0x97, 0xd4,
	0xf9, 0xe0, 0x76, 0x9f, 0xad, 0xd6, 0x3e, 0xac, 0xdb, 0xab, 0xe8, 0xd1, 0xcf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x42, 0x71, 0x07, 0x70, 0xc5, 0x04, 0x00, 0x00,
}

func (this *DataPacket) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DataPacket)
	if !ok {
		that2, ok := that.(DataPacket)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.GroupIdHash != that1.GroupIdHash {
		return false
	}
	if this.RawGroupId != that1.RawGroupId {
		return false
	}
	if this.Token != that1.Token {
		return false
	}
	if this.Source != that1.Source {
		return false
	}
	if this.DataType != that1.DataType {
		return false
	}
	if this.ConfigVersion != that1.ConfigVersion {
		return false
	}
	if this.HasError != that1.HasError {
		return false
	}
	if this.GroupKey != that1.GroupKey {
		return false
	}
	if this.PointCount != that1.PointCount {
		return false
	}
	if this.TraceStartTimeUnixNano != that1.TraceStartTimeUnixNano {
		return false
	}
	if this.TraceEndTimeUnixNano != that1.TraceEndTimeUnixNano {
		return false
	}
	if len(this.Points) != len(that1.Points) {
		return false
	}
	for i := range this.Points {
		if !this.Points[i].Equal(that1.Points[i]) {
			return false
		}
	}
	return true
}
func (this *DataPacketV2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DataPacketV2)
	if !ok {
		that2, ok := that.(DataPacketV2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.GroupIdHash != that1.GroupIdHash {
		return false
	}
	if this.RawGroupId != that1.RawGroupId {
		return false
	}
	if this.Token != that1.Token {
		return false
	}
	if this.Source != that1.Source {
		return false
	}
	if this.DataType != that1.DataType {
		return false
	}
	if this.ConfigVersion != that1.ConfigVersion {
		return false
	}
	if this.HasError != that1.HasError {
		return false
	}
	if this.GroupKey != that1.GroupKey {
		return false
	}
	if this.PointCount != that1.PointCount {
		return false
	}
	if this.TraceStartTimeUnixNano != that1.TraceStartTimeUnixNano {
		return false
	}
	if this.TraceEndTimeUnixNano != that1.TraceEndTimeUnixNano {
		return false
	}
	if len(this.RawPoints) != len(that1.RawPoints) {
		return false
	}
	for i := range this.RawPoints {
		if !bytes.Equal(this.RawPoints[i], that1.RawPoints[i]) {
			return false
		}
	}
	return true
}
func (this *DataBatch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DataBatch)
	if !ok {
		that2, ok := that.(DataBatch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CollectorId != that1.CollectorId {
		return false
	}
	if len(this.Packets) != len(that1.Packets) {
		return false
	}
	for i := range this.Packets {
		if !this.Packets[i].Equal(that1.Packets[i]) {
			return false
		}
	}
	return true
}
func (this *DataBatchV2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DataBatchV2)
	if !ok {
		that2, ok := that.(DataBatchV2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CollectorId != that1.CollectorId {
		return false
	}
	if len(this.Packets) != len(that1.Packets) {
		return false
	}
	for i := range this.Packets {
		if !this.Packets[i].Equal(that1.Packets[i]) {
			return false
		}
	}
	return true
}
func (this *DataPacket) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 16)
	s = append(s, "&aggregate.DataPacket{")
	s = append(s, "GroupIdHash: "+fmt.Sprintf("%#v", this.GroupIdHash)+",\n")
	s = append(s, "RawGroupId: "+fmt.Sprintf("%#v", this.RawGroupId)+",\n")
	s = append(s, "Token: "+fmt.Sprintf("%#v", this.Token)+",\n")
	s = append(s, "Source: "+fmt.Sprintf("%#v", this.Source)+",\n")
	s = append(s, "DataType: "+fmt.Sprintf("%#v", this.DataType)+",\n")
	s = append(s, "ConfigVersion: "+fmt.Sprintf("%#v", this.ConfigVersion)+",\n")
	s = append(s, "HasError: "+fmt.Sprintf("%#v", this.HasError)+",\n")
	s = append(s, "GroupKey: "+fmt.Sprintf("%#v", this.GroupKey)+",\n")
	s = append(s, "PointCount: "+fmt.Sprintf("%#v", this.PointCount)+",\n")
	s = append(s, "TraceStartTimeUnixNano: "+fmt.Sprintf("%#v", this.TraceStartTimeUnixNano)+",\n")
	s = append(s, "TraceEndTimeUnixNano: "+fmt.Sprintf("%#v", this.TraceEndTimeUnixNano)+",\n")
	if this.Points != nil {
		s = append(s, "Points: "+fmt.Sprintf("%#v", this.Points)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DataPacketV2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 16)
	s = append(s, "&aggregate.DataPacketV2{")
	s = append(s, "GroupIdHash: "+fmt.Sprintf("%#v", this.GroupIdHash)+",\n")
	s = append(s, "RawGroupId: "+fmt.Sprintf("%#v", this.RawGroupId)+",\n")
	s = append(s, "Token: "+fmt.Sprintf("%#v", this.Token)+",\n")
	s = append(s, "Source: "+fmt.Sprintf("%#v", this.Source)+",\n")
	s = append(s, "DataType: "+fmt.Sprintf("%#v", this.DataType)+",\n")
	s = append(s, "ConfigVersion: "+fmt.Sprintf("%#v", this.ConfigVersion)+",\n")
	s = append(s, "HasError: "+fmt.Sprintf("%#v", this.HasError)+",\n")
	s = append(s, "GroupKey: "+fmt.Sprintf("%#v", this.GroupKey)+",\n")
	s = append(s, "PointCount: "+fmt.Sprintf("%#v", this.PointCount)+",\n")
	s = append(s, "TraceStartTimeUnixNano: "+fmt.Sprintf("%#v", this.TraceStartTimeUnixNano)+",\n")
	s = append(s, "TraceEndTimeUnixNano: "+fmt.Sprintf("%#v", this.TraceEndTimeUnixNano)+",\n")
	s = append(s, "RawPoints: "+fmt.Sprintf("%#v", this.RawPoints)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DataBatch) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&aggregate.DataBatch{")
	s = append(s, "CollectorId: "+fmt.Sprintf("%#v", this.CollectorId)+",\n")
	if this.Packets != nil {
		s = append(s, "Packets: "+fmt.Sprintf("%#v", this.Packets)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DataBatchV2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&aggregate.DataBatchV2{")
	s = append(s, "CollectorId: "+fmt.Sprintf("%#v", this.CollectorId)+",\n")
	if this.Packets != nil {
		s = append(s, "Packets: "+fmt.Sprintf("%#v", this.Packets)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTsdata(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *DataPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Points) > 0 {
		for iNdEx := len(m.Points) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Points[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTsdata(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.TraceEndTimeUnixNano != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.TraceEndTimeUnixNano))
		i--
		dAtA[i] = 0x58
	}
	if m.TraceStartTimeUnixNano != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.TraceStartTimeUnixNano))
		i--
		dAtA[i] = 0x50
	}
	if m.PointCount != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.PointCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.GroupKey) > 0 {
		i -= len(m.GroupKey)
		copy(dAtA[i:], m.GroupKey)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.GroupKey)))
		i--
		dAtA[i] = 0x42
	}
	if m.HasError {
		i--
		if m.HasError {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.ConfigVersion != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.ConfigVersion))
		i--
		dAtA[i] = 0x30
	}
	if len(m.DataType) > 0 {
		i -= len(m.DataType)
		copy(dAtA[i:], m.DataType)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.DataType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RawGroupId) > 0 {
		i -= len(m.RawGroupId)
		copy(dAtA[i:], m.RawGroupId)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.RawGroupId)))
		i--
		dAtA[i] = 0x12
	}
	if m.GroupIdHash != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.GroupIdHash))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DataPacketV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataPacketV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataPacketV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RawPoints) > 0 {
		for iNdEx := len(m.RawPoints) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RawPoints[iNdEx])
			copy(dAtA[i:], m.RawPoints[iNdEx])
			i = encodeVarintTsdata(dAtA, i, uint64(len(m.RawPoints[iNdEx])))
			i--
			dAtA[i] = 0x62
		}
	}
	if m.TraceEndTimeUnixNano != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.TraceEndTimeUnixNano))
		i--
		dAtA[i] = 0x58
	}
	if m.TraceStartTimeUnixNano != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.TraceStartTimeUnixNano))
		i--
		dAtA[i] = 0x50
	}
	if m.PointCount != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.PointCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.GroupKey) > 0 {
		i -= len(m.GroupKey)
		copy(dAtA[i:], m.GroupKey)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.GroupKey)))
		i--
		dAtA[i] = 0x42
	}
	if m.HasError {
		i--
		if m.HasError {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.ConfigVersion != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.ConfigVersion))
		i--
		dAtA[i] = 0x30
	}
	if len(m.DataType) > 0 {
		i -= len(m.DataType)
		copy(dAtA[i:], m.DataType)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.DataType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RawGroupId) > 0 {
		i -= len(m.RawGroupId)
		copy(dAtA[i:], m.RawGroupId)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.RawGroupId)))
		i--
		dAtA[i] = 0x12
	}
	if m.GroupIdHash != 0 {
		i = encodeVarintTsdata(dAtA, i, uint64(m.GroupIdHash))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DataBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Packets) > 0 {
		for iNdEx := len(m.Packets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Packets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTsdata(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CollectorId) > 0 {
		i -= len(m.CollectorId)
		copy(dAtA[i:], m.CollectorId)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.CollectorId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DataBatchV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataBatchV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataBatchV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Packets) > 0 {
		for iNdEx := len(m.Packets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Packets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTsdata(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CollectorId) > 0 {
		i -= len(m.CollectorId)
		copy(dAtA[i:], m.CollectorId)
		i = encodeVarintTsdata(dAtA, i, uint64(len(m.CollectorId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTsdata(dAtA []byte, offset int, v uint64) int {
	offset -= sovTsdata(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DataPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GroupIdHash != 0 {
		n += 1 + sovTsdata(uint64(m.GroupIdHash))
	}
	l = len(m.RawGroupId)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	l = len(m.DataType)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	if m.ConfigVersion != 0 {
		n += 1 + sovTsdata(uint64(m.ConfigVersion))
	}
	if m.HasError {
		n += 2
	}
	l = len(m.GroupKey)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	if m.PointCount != 0 {
		n += 1 + sovTsdata(uint64(m.PointCount))
	}
	if m.TraceStartTimeUnixNano != 0 {
		n += 1 + sovTsdata(uint64(m.TraceStartTimeUnixNano))
	}
	if m.TraceEndTimeUnixNano != 0 {
		n += 1 + sovTsdata(uint64(m.TraceEndTimeUnixNano))
	}
	if len(m.Points) > 0 {
		for _, e := range m.Points {
			l = e.Size()
			n += 1 + l + sovTsdata(uint64(l))
		}
	}
	return n
}

func (m *DataPacketV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GroupIdHash != 0 {
		n += 1 + sovTsdata(uint64(m.GroupIdHash))
	}
	l = len(m.RawGroupId)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	l = len(m.DataType)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	if m.ConfigVersion != 0 {
		n += 1 + sovTsdata(uint64(m.ConfigVersion))
	}
	if m.HasError {
		n += 2
	}
	l = len(m.GroupKey)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	if m.PointCount != 0 {
		n += 1 + sovTsdata(uint64(m.PointCount))
	}
	if m.TraceStartTimeUnixNano != 0 {
		n += 1 + sovTsdata(uint64(m.TraceStartTimeUnixNano))
	}
	if m.TraceEndTimeUnixNano != 0 {
		n += 1 + sovTsdata(uint64(m.TraceEndTimeUnixNano))
	}
	if len(m.RawPoints) > 0 {
		for _, b := range m.RawPoints {
			l = len(b)
			n += 1 + l + sovTsdata(uint64(l))
		}
	}
	return n
}

func (m *DataBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CollectorId)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	if len(m.Packets) > 0 {
		for _, e := range m.Packets {
			l = e.Size()
			n += 1 + l + sovTsdata(uint64(l))
		}
	}
	return n
}

func (m *DataBatchV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CollectorId)
	if l > 0 {
		n += 1 + l + sovTsdata(uint64(l))
	}
	if len(m.Packets) > 0 {
		for _, e := range m.Packets {
			l = e.Size()
			n += 1 + l + sovTsdata(uint64(l))
		}
	}
	return n
}

func sovTsdata(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTsdata(x uint64) (n int) {
	return sovTsdata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *DataPacket) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForPoints := "[]*PBPoint{"
	for _, f := range this.Points {
		repeatedStringForPoints += strings.Replace(fmt.Sprintf("%v", f), "PBPoint", "point.PBPoint", 1) + ","
	}
	repeatedStringForPoints += "}"
	s := strings.Join([]string{`&DataPacket{`,
		`GroupIdHash:` + fmt.Sprintf("%v", this.GroupIdHash) + `,`,
		`RawGroupId:` + fmt.Sprintf("%v", this.RawGroupId) + `,`,
		`Token:` + fmt.Sprintf("%v", this.Token) + `,`,
		`Source:` + fmt.Sprintf("%v", this.Source) + `,`,
		`DataType:` + fmt.Sprintf("%v", this.DataType) + `,`,
		`ConfigVersion:` + fmt.Sprintf("%v", this.ConfigVersion) + `,`,
		`HasError:` + fmt.Sprintf("%v", this.HasError) + `,`,
		`GroupKey:` + fmt.Sprintf("%v", this.GroupKey) + `,`,
		`PointCount:` + fmt.Sprintf("%v", this.PointCount) + `,`,
		`TraceStartTimeUnixNano:` + fmt.Sprintf("%v", this.TraceStartTimeUnixNano) + `,`,
		`TraceEndTimeUnixNano:` + fmt.Sprintf("%v", this.TraceEndTimeUnixNano) + `,`,
		`Points:` + repeatedStringForPoints + `,`,
		`}`,
	}, "")
	return s
}
func (this *DataPacketV2) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DataPacketV2{`,
		`GroupIdHash:` + fmt.Sprintf("%v", this.GroupIdHash) + `,`,
		`RawGroupId:` + fmt.Sprintf("%v", this.RawGroupId) + `,`,
		`Token:` + fmt.Sprintf("%v", this.Token) + `,`,
		`Source:` + fmt.Sprintf("%v", this.Source) + `,`,
		`DataType:` + fmt.Sprintf("%v", this.DataType) + `,`,
		`ConfigVersion:` + fmt.Sprintf("%v", this.ConfigVersion) + `,`,
		`HasError:` + fmt.Sprintf("%v", this.HasError) + `,`,
		`GroupKey:` + fmt.Sprintf("%v", this.GroupKey) + `,`,
		`PointCount:` + fmt.Sprintf("%v", this.PointCount) + `,`,
		`TraceStartTimeUnixNano:` + fmt.Sprintf("%v", this.TraceStartTimeUnixNano) + `,`,
		`TraceEndTimeUnixNano:` + fmt.Sprintf("%v", this.TraceEndTimeUnixNano) + `,`,
		`RawPoints:` + fmt.Sprintf("%v", this.RawPoints) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DataBatch) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForPackets := "[]*DataPacket{"
	for _, f := range this.Packets {
		repeatedStringForPackets += strings.Replace(f.String(), "DataPacket", "DataPacket", 1) + ","
	}
	repeatedStringForPackets += "}"
	s := strings.Join([]string{`&DataBatch{`,
		`CollectorId:` + fmt.Sprintf("%v", this.CollectorId) + `,`,
		`Packets:` + repeatedStringForPackets + `,`,
		`}`,
	}, "")
	return s
}
func (this *DataBatchV2) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForPackets := "[]*DataPacketV2{"
	for _, f := range this.Packets {
		repeatedStringForPackets += strings.Replace(f.String(), "DataPacketV2", "DataPacketV2", 1) + ","
	}
	repeatedStringForPackets += "}"
	s := strings.Join([]string{`&DataBatchV2{`,
		`CollectorId:` + fmt.Sprintf("%v", this.CollectorId) + `,`,
		`Packets:` + repeatedStringForPackets + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTsdata(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *DataPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTsdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupIdHash", wireType)
			}
			m.GroupIdHash = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupIdHash |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawGroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawGroupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigVersion", wireType)
			}
			m.ConfigVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfigVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasError", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasError = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PointCount", wireType)
			}
			m.PointCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PointCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceStartTimeUnixNano", wireType)
			}
			m.TraceStartTimeUnixNano = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceStartTimeUnixNano |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceEndTimeUnixNano", wireType)
			}
			m.TraceEndTimeUnixNano = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceEndTimeUnixNano |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Points", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Points = append(m.Points, &point.PBPoint{})
			if err := m.Points[len(m.Points)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTsdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTsdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataPacketV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTsdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataPacketV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataPacketV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupIdHash", wireType)
			}
			m.GroupIdHash = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupIdHash |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawGroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawGroupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigVersion", wireType)
			}
			m.ConfigVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfigVersion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasError", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasError = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PointCount", wireType)
			}
			m.PointCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PointCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceStartTimeUnixNano", wireType)
			}
			m.TraceStartTimeUnixNano = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceStartTimeUnixNano |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceEndTimeUnixNano", wireType)
			}
			m.TraceEndTimeUnixNano = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceEndTimeUnixNano |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawPoints", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawPoints = append(m.RawPoints, make([]byte, postIndex-iNdEx))
			copy(m.RawPoints[len(m.RawPoints)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTsdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTsdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTsdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Packets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Packets = append(m.Packets, &DataPacket{})
			if err := m.Packets[len(m.Packets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTsdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTsdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataBatchV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTsdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataBatchV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataBatchV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Packets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTsdata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTsdata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Packets = append(m.Packets, &DataPacketV2{})
			if err := m.Packets[len(m.Packets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTsdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTsdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTsdata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTsdata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTsdata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTsdata
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTsdata
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTsdata
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTsdata        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTsdata          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTsdata = fmt.Errorf("proto: unexpected end of group")
)
